amazona/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('apps.books.urls', namespace='books')),
    # url(r'^reviews/', include('apps.reviews.urls', namespace='reviews')),
    url(r'^', include('apps.users.urls', namespace='users')),
]

apps/books/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^$', views.book_list, name='list'),
	url(r'^add/$', views.add_book, name='add'),
	url(r'^create/$', views.create_book, name='create'),
	url(r'^(?P<book_id>[0-9]+)/$', views.show_book, name='show'),
	url(r'^(?P<book_id>[0-9]+)/review/create/$', views.add_review, name='add_review'),
	url(r'^(?P<book_id>[0-9]+)/review/(?P<review_id>[0-9]+)/$', views.delete_review, name='delete_review'),
]

apps/books/models.py
from django.db import models

from apps.users.models import User
# Create your models here.



class Book(models.Model):

	title = models.CharField(max_length=255, unique=True)
	summary = models.TextField()

	date_created = models.DateTimeField(auto_now_add=True)
	date_updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title


class Review(models.Model):
	
	user = models.ForeignKey(User)
	book = models.ForeignKey(Book)

	subject = models.CharField(max_length=255)
	comment = models.TextField()

	rating = models.IntegerField(default=0)

	date_created = models.DateTimeField(auto_now_add=True)
	date_updated = models.DateTimeField(auto_now=True)

class Author(models.Model):

	books = models.ManyToManyField(Book)

	name = models.CharField(max_length=255, unique=True)

	date_created = models.DateTimeField(auto_now_add=True)
	date_updated = models.DateTimeField(auto_now=True)



	def __str__(self):
		return self.name

apps/books/forms.py
from django import forms
from django.core.exceptions import ValidationError

from apps.books.models import Author
from apps.books.validators import unique_author, unique_title, author_name_validation
from apps.books.validators import author_name_validation


class AddBookForm(forms.Form):

	def __init__(self, *args, **kwargs):
		super(AddBookForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

	title = forms.CharField(
		min_length = 5,
		max_length = 255,
		required = True,
		validators = [unique_title,]
		)

	summary = forms.CharField(
		min_length = 50,
		widget = forms.Textarea
		)



class AddAuthorForm(forms.Form):

	def __init__(self, *args, **kwargs):
		super(AddAuthorForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

	authors = forms.ModelMultipleChoiceField(
		required = False,
		# widget = forms.CheckboxSelectMultiple,
		queryset = Author.objects
		)

	add_new_author = forms.CharField(
		required = False,
		min_length = 5,
		max_length = 255,
		validators = [unique_author, author_name_validation]
		)


	def clean_add_new_author(self):

		authors = self.cleaned_data.get('authors')
		new_author = self.cleaned_data.get('add_new_author')

		if len(authors) == 0 and new_author == '':
			raise ValidationError('Please add a new author or select existing authors.')
		else:
			return new_author


class AddReviewForm(forms.Form):

	def __init__(self, *args, **kwargs):
		super(AddReviewForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

	user = forms.CharField(
		widget = forms.TextInput(attrs = {'readonly' : 'readonly'})
		)

	subject = forms.CharField(
		min_length = 5,
		max_length = 255,
		required = True
		)

	comment = forms.CharField(
		min_length = 15,
		required = True,
		widget = forms.Textarea
		)

	rating = forms.IntegerField(
		help_text = 'Rating ranges from 1 to 5.'
		)


	def clean_rating(self):

		rating = self.cleaned_data.get('rating', None)

		if rating is not None:

			if int(rating) in [1, 2, 3, 4, 5]:
				return rating

			else:
				raise ValidationError('Your rating is too high/low.')

		else:
			raise ValidationError('Please rate the book from 1 - 5.')

apps/books/views.py
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from apps.books.forms import AddBookForm, AddReviewForm, AddAuthorForm
from apps.users.models import User
from apps.books.models import Book, Review, Author

# Create your views here.


def book_list(request):

	books = Book.objects.all()

	other_books = [book for book in books if len(book.review_set.all()) > 0]

	latest_book_reviews = sorted(
		other_books,
		key = lambda book: book.review_set.last().date_created,
		reverse = True
		)

	context = {
	'books' : latest_book_reviews[:3],
	'other_books' : other_books,
	}
	return render(request, 'books/pages/list.html', context)


def add_book(request):

	if 'user' not in request.session:
		messages.error(request, 'Login first before giving a review.')
		return HttpResponseRedirect( reverse('users:index') )

	user_alias = request.session['user']['alias']
	
	book_form = AddBookForm()
	review_form = AddReviewForm(initial = {'user' : user_alias})
	author_form = AddAuthorForm()

	context = {
	'book_form' : book_form,
	'review_form' : review_form,
	'author_form' : author_form,
	}
	return render(request, 'books/pages/add.html', context)


def create_book(request):

	if 'user' not in request.session:
		messages.error(request, 'You are not yet logged in.')
		return HttpResponseRedirect( reverse('users:index') )
	
	if request.method == 'POST':
		
		book_form = AddBookForm(request.POST)
		review_form = AddReviewForm(request.POST)
		author_form = AddAuthorForm(request.POST)

		user = User.objects.filter(
			email = request.session['user']['email']
			).first()

		number_of_errors = 0

		if book_form.is_valid():
			print('book pass!')

			new_book = Book.objects.create(
				title = book_form.cleaned_data.get('title'),
				summary = book_form.cleaned_data.get('summary')
				)

		else:
			print(book_form.errors)
			messages.error(request, book_form.errors)
			number_of_errors += 1

			return HttpResponseRedirect( reverse('books:add') )


		if review_form.is_valid():
			print('review pass!')

			new_review = Review.objects.create(
				user = user,
				book = new_book,
				subject = review_form.cleaned_data.get('subject'),
				comment = review_form.cleaned_data.get('comment'),
				rating = review_form.cleaned_data.get('rating')
				)


		else:
			print(review_form.errors)
			messages.error(request, review_form.errors)
			number_of_errors += 1

			new_book.delete()

			return HttpResponseRedirect( reverse('books:add') )


		if author_form.is_valid():
			print('author pass!')

			new_author = author_form.cleaned_data.get('add_new_author', None)
			existing_authors = author_form.cleaned_data.get('authors', None)

			if new_author is not None and new_author.replace(' ', '') != '':

				added_author = Author.objects.create(
					name = new_author
					)

				new_book.author_set.add(added_author)
				

			if existing_authors is not None and len(existing_authors) != 0:

				for i in existing_authors:
					new_book.author_set.add(i)

				print('Authors added to the new book.')

		else:
			print(author_form.errors)
			messages.error(request, author_form.errors)
			number_of_errors += 1

			new_book.delete()
			new_review.delete()

			return HttpResponseRedirect( reverse('books:add') )


		if number_of_errors > 0:
			messages.error(request, 'Failed to validate entries due to error.')
			return HttpResponseRedirect( reverse('books:add') )

		else:
			messages.success(request, 'Creation complete!')
			return HttpResponseRedirect( reverse('books:show', args=(new_book.id,)) )


	else:
		messages.error(request, 'You are not allowed to this page.')
		return HttpResponseRedirect( reverse('books:add') )




def show_book(request, book_id):

	book = Book.objects.filter(id = book_id).first()

	if book is not None:

		if 'user' in request.session:
			user_alias = request.session['user']['alias']
			review_form = AddReviewForm(initial={'user' : user_alias})

		else:
			user_alias = None
			review_form = None

		total_rating = 0

		reviews = book.review_set.all()

		for review in reviews:
			total_rating += review.rating

		try:
			total_rating /= len(reviews)
		except ZeroDivisionError:
			total_rating = 'Not yet rated.'

		context = {
		'book' : book,
		'reviews' : reviews,
		'total_rating' : total_rating,
		'review_form' : review_form,
		}
		return render(request, 'books/pages/show.html', context)

	else:
		messages.error(request, 'Invalid book ID.')
		return HttpResponseRedirect( reverse('books:list') )



def delete_review(request, book_id, review_id):

	if 'user' in request.session:

		review = Review.objects.filter(id = review_id).first()
		user_id = request.session['user']['id']

		if review.user.id == user_id:
			
			review.delete()
			messages.success(request, 'You have successfully deleted your review.')
			return HttpResponseRedirect( reverse('books:show', args=(book_id,)) )

		else:
			messages.error(request, 'You are not the owner of this review.')
			return HttpResponseRedirect( reverse('books:show', args=(book_id,)) )


	else:
		messages.error(request, 'Please login first before accessing this link.')
		return HttpResponseRedirect( reverse('users:index') )



def add_review(request, book_id):

	if request.method == 'POST':

		if 'user' in request.session:

			review_form = AddReviewForm(request.POST)

			if review_form.is_valid():

				user = User.objects.filter(
					alias = review_form.cleaned_data.get('user')
					).first()

				book = Book.objects.filter(id = book_id).first()
				
				new_review = Review.objects.create(
					user = user,
					book = book,
					subject = review_form.cleaned_data.get('subject'),
					comment = review_form.cleaned_data.get('comment'),
					rating = review_form.cleaned_data.get('rating')
					)

				messages.success(request, 'Review creation success!')
				return HttpResponseRedirect( reverse('books:show', args=(book_id,)))

			else:
				messages.error(review_form.errors)
				return HttpResponseRedirect( reverse('books:show', args=(book_id,)))

		else:
			messages.error(request, 'Please login first before accessing this link.')
			return HttpResponseRedirect( reverse('books:show', args=(book_id,)))

	else:
		messages.error(request, 'You are not allowed here.')
		return HttpResponseRedirect( reverse('books:show', args=(book_id,)) )

apps/books/templates/books/pages/add.html
{% extends 'books/base.html' %}

{% block title %}
<title>Books Home</title>
{% endblock %}

{% block main_content %}

<main class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			
			<div class="col-md-6">
				<form action="{% url 'books:create' %}" method="POST">
					{% csrf_token %}

					<table class="table">
						{{ book_form.as_table }}
					</table>

					<table class="table">
						{{ author_form.as_table }}
					</table>

					<table class="table">
						{{ review_form.as_table }}
					</table>

					<input type="submit" name="submit" value="Submit" class="btn btn-success pull-right">

				</form>
			</div>

		</div>
	</div>
</main>

{% endblock %}

apps/books/templates/books/pages/list.html
{% extends 'books/base.html' %}

{% block title %}
<title>Books Home</title>
{% endblock %}

{% block main_content %}

<main class="container-fluid">
	<div class="row">
		<div class="col-md-6">
			{% if request.session.user %}
			<h1>Welcome, {{ request.session.user.name }}</h1>
			{% else %}
			<h1>Welcome to Amazona!</h1>
			{% endif %}

			{% if books %}
			<h3>Recent Book Reviews</h3>

			<dl>

				{% for book in books %}
				<hr>
				<dt><a href="{% url 'books:show' book.id %}">{{ book.title }}</a></dt>
				<dd>Ratings: {{ total_rating }}</dd>
				<dd>
					<a href="{% url 'users:show' book.review_set.last.user.id %}">{{ book.review_set.last.user.name }}</a> says: {{ book.review_set.last.comment|truncatechars:100 }}
				</dd>
				<dd>
					Posted on {{ book.review_set.last.date_created }}
				</dd>
				{% endfor %}

			</dl>
			{% else %}
				{% if request.session.user %}
				<h2>No book listed yet. Please add a new book with its review.</h2>
				{% else %}
				<h2>No book listed yet. Please login first to add a new book and its review.</h2>
				{% endif%}
			{% endif %}
		</div>

		<div class="col-md-6">
			{% if other_books %}
			<h3>Other books with reviews</h3>
			<div class="col-md-12">
				<ul>
					{% for book in other_books %}
					<li><a href="{% url 'books:show' book.id %}">{{ book.title }}</a></li>
					{% endfor %}
				</ul>
			</div>
			{% endif %}
		</div>

	</div>
</main>

{% endblock %}

apps/books/templates/books/pages/show.html
{% extends 'books/base.html' %}

{% block main_content %}

<div class="col-md-6">
		
	<h1>{{ book.title }}</h1>
	<p>Total Ratings: <strong>{{ total_rating }}</strong></p>
	<p>Author/s: <strong>{{ book.author_set.all | join:", "}}</strong></p>

	<dl>
		{% for review in reviews %}
		<hr>
		<dt>Ratings: {{ review.rating }}</dt>
		<dd>
			<a href="{% url 'users:show' review.user.id %}">{{ review.user.name }}</a> says: {{ review.comment|truncatechars:100 }}
		</dd>
		<dd>
			Posted on {{ review.date_created }} {% if request.session.user.id == review.user.id %}<a href="{% url 'books:delete_review' book_id=book.id review_id=review.id %}">Delete this review</a>{% endif %}
		</dd>

		{% endfor %}
	</dl>
</div>	



<div class="col-md-6">
	{% if request.session.is_authenticated %}
	<form action="{% url 'books:add_review' book.id %}" method="POST">
		{% csrf_token %}

		<table class="table">
			{{ review_form.as_table }}
		</table>

		<input type="submit" name="submit" value="Submit Review" class="btn btn-success pull-right">

	</form>
	{% endif %}
</div>

{% endblock %}